import { ENV } from './environment';

export const TOKEN_COOKIE_KEY = ENV.API_TOKEN_KEY;
export const TOKEN_DELETED_KEY = ENV.DELETED_TOKEN_CONFIRMATION_KEY;
export const TOKEN_DELETED_VALUE = ENV.DELETED_TOKEN_CONFIRMATION_VALUE;
